import { TMConfig } from "../types";

export const threeEqualLength: TMConfig = {
  title: "Tres cadenas de igual longitud",
  description:
    "Reconoce a^n b^n c^n. Por cada a marca un b y un c correspondientes (X/Y/Z), repitiendo hasta agotar las a y verificando que no sobren símbolos.",
  tape: ["a", "a", "b", "b", "c", "c"],
  initialState: "q0",
  blankSymbol: "_",
  transitions: [
    {
      currentState: "q0",
      readSymbol: "X",
      writeSymbol: "X",
      move: "R",
      nextState: "q0",
    },
    {
      currentState: "q0",
      readSymbol: "a",
      writeSymbol: "X",
      move: "R",
      nextState: "q1",
    },
    {
      currentState: "q0",
      readSymbol: "b",
      writeSymbol: "b",
      move: "N",
      nextState: "qCheckB",
    },
    {
      currentState: "q0",
      readSymbol: "_",
      writeSymbol: "_",
      move: "N",
      nextState: "accept",
    },

    {
      currentState: "q1",
      readSymbol: "a",
      writeSymbol: "a",
      move: "R",
      nextState: "q1",
    },
    {
      currentState: "q1",
      readSymbol: "X",
      writeSymbol: "X",
      move: "R",
      nextState: "q1",
    },
    {
      currentState: "q1",
      readSymbol: "Y",
      writeSymbol: "Y",
      move: "R",
      nextState: "q1",
    },
    {
      currentState: "q1",
      readSymbol: "b",
      writeSymbol: "Y",
      move: "R",
      nextState: "q2",
    },
    {
      currentState: "q1",
      readSymbol: "c",
      writeSymbol: "c",
      move: "N",
      nextState: "reject",
    },
    {
      currentState: "q1",
      readSymbol: "_",
      writeSymbol: "_",
      move: "N",
      nextState: "reject",
    },

    {
      currentState: "q2",
      readSymbol: "b",
      writeSymbol: "b",
      move: "R",
      nextState: "q2",
    },
    {
      currentState: "q2",
      readSymbol: "Y",
      writeSymbol: "Y",
      move: "R",
      nextState: "q2",
    },
    {
      currentState: "q2",
      readSymbol: "Z",
      writeSymbol: "Z",
      move: "R",
      nextState: "q2",
    },
    {
      currentState: "q2",
      readSymbol: "c",
      writeSymbol: "Z",
      move: "L",
      nextState: "qBack",
    },
    {
      currentState: "q2",
      readSymbol: "_",
      writeSymbol: "_",
      move: "N",
      nextState: "reject",
    },

    {
      currentState: "qBack",
      readSymbol: "a",
      writeSymbol: "a",
      move: "L",
      nextState: "qBack",
    },
    {
      currentState: "qBack",
      readSymbol: "b",
      writeSymbol: "b",
      move: "L",
      nextState: "qBack",
    },
    {
      currentState: "qBack",
      readSymbol: "c",
      writeSymbol: "c",
      move: "L",
      nextState: "qBack",
    },
    {
      currentState: "qBack",
      readSymbol: "X",
      writeSymbol: "X",
      move: "L",
      nextState: "qBack",
    },
    {
      currentState: "qBack",
      readSymbol: "Y",
      writeSymbol: "Y",
      move: "L",
      nextState: "qBack",
    },
    {
      currentState: "qBack",
      readSymbol: "Z",
      writeSymbol: "Z",
      move: "L",
      nextState: "qBack",
    },
    {
      currentState: "qBack",
      readSymbol: "_",
      writeSymbol: "_",
      move: "R",
      nextState: "q0",
    },

    {
      currentState: "qCheckB",
      readSymbol: "X",
      writeSymbol: "X",
      move: "R",
      nextState: "qCheckB",
    },
    {
      currentState: "qCheckB",
      readSymbol: "Y",
      writeSymbol: "Y",
      move: "R",
      nextState: "qCheckB",
    },
    {
      currentState: "qCheckB",
      readSymbol: "Z",
      writeSymbol: "Z",
      move: "R",
      nextState: "qCheckB",
    },
    {
      currentState: "qCheckB",
      readSymbol: "b",
      writeSymbol: "b",
      move: "N",
      nextState: "reject",
    },
    {
      currentState: "qCheckB",
      readSymbol: "c",
      writeSymbol: "c",
      move: "N",
      nextState: "reject",
    },
    {
      currentState: "qCheckB",
      readSymbol: "_",
      writeSymbol: "_",
      move: "N",
      nextState: "accept",
    },
  ],
};
