import { TMConfig } from "../types";

export const divisibleBy3Base10: TMConfig = {
  title: "Divisible por 3 (base 10)",
  description:
    "Acepta números decimales divisibles por 3. Usa el criterio de suma de dígitos: mantiene (suma mod 3) mientras lee la cinta.",
  tape: ["1", "2"],
  initialState: "s0",
  blankSymbol: "_",
  transitions: [
    // s0: sum mod 3 = 0
    {
      currentState: "s0",
      readSymbol: "0",
      writeSymbol: "0",
      move: "R",
      nextState: "s0",
    },
    {
      currentState: "s0",
      readSymbol: "3",
      writeSymbol: "3",
      move: "R",
      nextState: "s0",
    },
    {
      currentState: "s0",
      readSymbol: "6",
      writeSymbol: "6",
      move: "R",
      nextState: "s0",
    },
    {
      currentState: "s0",
      readSymbol: "9",
      writeSymbol: "9",
      move: "R",
      nextState: "s0",
    },
    {
      currentState: "s0",
      readSymbol: "1",
      writeSymbol: "1",
      move: "R",
      nextState: "s1",
    },
    {
      currentState: "s0",
      readSymbol: "4",
      writeSymbol: "4",
      move: "R",
      nextState: "s1",
    },
    {
      currentState: "s0",
      readSymbol: "7",
      writeSymbol: "7",
      move: "R",
      nextState: "s1",
    },
    {
      currentState: "s0",
      readSymbol: "2",
      writeSymbol: "2",
      move: "R",
      nextState: "s2",
    },
    {
      currentState: "s0",
      readSymbol: "5",
      writeSymbol: "5",
      move: "R",
      nextState: "s2",
    },
    {
      currentState: "s0",
      readSymbol: "8",
      writeSymbol: "8",
      move: "R",
      nextState: "s2",
    },
    {
      currentState: "s0",
      readSymbol: "_",
      writeSymbol: "_",
      move: "N",
      nextState: "accept",
    },

    // s1: sum mod 3 = 1
    {
      currentState: "s1",
      readSymbol: "0",
      writeSymbol: "0",
      move: "R",
      nextState: "s1",
    },
    {
      currentState: "s1",
      readSymbol: "3",
      writeSymbol: "3",
      move: "R",
      nextState: "s1",
    },
    {
      currentState: "s1",
      readSymbol: "6",
      writeSymbol: "6",
      move: "R",
      nextState: "s1",
    },
    {
      currentState: "s1",
      readSymbol: "9",
      writeSymbol: "9",
      move: "R",
      nextState: "s1",
    },
    {
      currentState: "s1",
      readSymbol: "1",
      writeSymbol: "1",
      move: "R",
      nextState: "s2",
    },
    {
      currentState: "s1",
      readSymbol: "4",
      writeSymbol: "4",
      move: "R",
      nextState: "s2",
    },
    {
      currentState: "s1",
      readSymbol: "7",
      writeSymbol: "7",
      move: "R",
      nextState: "s2",
    },
    {
      currentState: "s1",
      readSymbol: "2",
      writeSymbol: "2",
      move: "R",
      nextState: "s0",
    },
    {
      currentState: "s1",
      readSymbol: "5",
      writeSymbol: "5",
      move: "R",
      nextState: "s0",
    },
    {
      currentState: "s1",
      readSymbol: "8",
      writeSymbol: "8",
      move: "R",
      nextState: "s0",
    },
    {
      currentState: "s1",
      readSymbol: "_",
      writeSymbol: "_",
      move: "N",
      nextState: "reject",
    },

    // s2: sum mod 3 = 2
    {
      currentState: "s2",
      readSymbol: "0",
      writeSymbol: "0",
      move: "R",
      nextState: "s2",
    },
    {
      currentState: "s2",
      readSymbol: "3",
      writeSymbol: "3",
      move: "R",
      nextState: "s2",
    },
    {
      currentState: "s2",
      readSymbol: "6",
      writeSymbol: "6",
      move: "R",
      nextState: "s2",
    },
    {
      currentState: "s2",
      readSymbol: "9",
      writeSymbol: "9",
      move: "R",
      nextState: "s2",
    },
    {
      currentState: "s2",
      readSymbol: "1",
      writeSymbol: "1",
      move: "R",
      nextState: "s0",
    },
    {
      currentState: "s2",
      readSymbol: "4",
      writeSymbol: "4",
      move: "R",
      nextState: "s0",
    },
    {
      currentState: "s2",
      readSymbol: "7",
      writeSymbol: "7",
      move: "R",
      nextState: "s0",
    },
    {
      currentState: "s2",
      readSymbol: "2",
      writeSymbol: "2",
      move: "R",
      nextState: "s1",
    },
    {
      currentState: "s2",
      readSymbol: "5",
      writeSymbol: "5",
      move: "R",
      nextState: "s1",
    },
    {
      currentState: "s2",
      readSymbol: "8",
      writeSymbol: "8",
      move: "R",
      nextState: "s1",
    },
    {
      currentState: "s2",
      readSymbol: "_",
      writeSymbol: "_",
      move: "N",
      nextState: "reject",
    },
  ],
};
